#############################################################################
# Makefile for building: qigsaw
# Generated by qmake (2.01a) (Qt 4.8.5) on: ?? ??? 17 17:51:32 2013
# Project:  qigsaw.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix -o Makefile qigsaw.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1,--sort-common,--as-needed,-z,relro -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lasound -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		SquareCutter.cpp \
		RectCutter.cpp \
		QuadCutter.cpp \
		Piece.cpp \
		NoRotationsShuffler.cpp \
		MultiPiece.cpp \
		Knob.cpp \
		JigUtil.cpp \
		JigShuffler.cpp \
		JigsawCutter.cpp \
		IGap.cpp \
		FreeShuffler.cpp \
		FreeCenterShuffler.cpp \
		exceptions.cpp \
		ClassicCutter.cpp \
		Classic4Cutter.cpp \
		ByColorShuffler.cpp \
		newdialog.cpp \
		jigsawaboutbox.cpp \
		mainwidget.cpp \
		previewframe.cpp \
		finaldialog.cpp \
		preview.cpp \
		aqsound.cpp \
		qpreviewfiledialog.cpp moc_mainwindow.cpp \
		moc_newdialog.cpp \
		moc_jigsawaboutbox.cpp \
		moc_mainwidget.cpp \
		moc_previewframe.cpp \
		moc_finaldialog.cpp \
		moc_aqsound.cpp \
		moc_qpreviewfiledialog.cpp \
		qrc_qigsaw.cpp
OBJECTS       = main.o \
		mainwindow.o \
		SquareCutter.o \
		RectCutter.o \
		QuadCutter.o \
		Piece.o \
		NoRotationsShuffler.o \
		MultiPiece.o \
		Knob.o \
		JigUtil.o \
		JigShuffler.o \
		JigsawCutter.o \
		IGap.o \
		FreeShuffler.o \
		FreeCenterShuffler.o \
		exceptions.o \
		ClassicCutter.o \
		Classic4Cutter.o \
		ByColorShuffler.o \
		newdialog.o \
		jigsawaboutbox.o \
		mainwidget.o \
		previewframe.o \
		finaldialog.o \
		preview.o \
		aqsound.o \
		qpreviewfiledialog.o \
		moc_mainwindow.o \
		moc_newdialog.o \
		moc_jigsawaboutbox.o \
		moc_mainwidget.o \
		moc_previewframe.o \
		moc_finaldialog.o \
		moc_aqsound.o \
		moc_qpreviewfiledialog.o \
		qrc_qigsaw.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		qigsaw.pro
QMAKE_TARGET  = qigsaw
DESTDIR       = 
TARGET        = qigsaw

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_NewDialog.h ui_jigsawaboutbox.h ui_mainwidget.h ui_previewframe.h ui_finaldialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qigsaw.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix -o Makefile qigsaw.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix -o Makefile qigsaw.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qigsaw1.0.0 || $(MKDIR) .tmp/qigsaw1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qigsaw1.0.0/ && $(COPY_FILE) --parents mainwindow.h SquareCutter.h RectCutter.h QuadCutter.h Piece.h NoRotationsShuffler.h MultiPiece.h Knob.h JigUtil.h JigShuffler.h JigsawCutter.h IGap.h FreeShuffler.h FreeCenterShuffler.h exceptions.h ClassicCutter.h Classic4Cutter.h ByColorShuffler.h newdialog.h jigsawaboutbox.h TDArray.h mainwidget.h previewframe.h finaldialog.h preview.h aqsound.h qpreviewfiledialog.h .tmp/qigsaw1.0.0/ && $(COPY_FILE) --parents qigsaw.qrc .tmp/qigsaw1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp SquareCutter.cpp RectCutter.cpp QuadCutter.cpp Piece.cpp NoRotationsShuffler.cpp MultiPiece.cpp Knob.cpp JigUtil.cpp JigShuffler.cpp JigsawCutter.cpp IGap.cpp FreeShuffler.cpp FreeCenterShuffler.cpp exceptions.cpp ClassicCutter.cpp Classic4Cutter.cpp ByColorShuffler.cpp newdialog.cpp jigsawaboutbox.cpp mainwidget.cpp previewframe.cpp finaldialog.cpp preview.cpp aqsound.cpp qpreviewfiledialog.cpp .tmp/qigsaw1.0.0/ && $(COPY_FILE) --parents mainwindow.ui NewDialog.ui jigsawaboutbox.ui mainwidget.ui previewframe.ui finaldialog.ui .tmp/qigsaw1.0.0/ && $(COPY_FILE) --parents qigsaw_ru.ts qigsaw_be.ts .tmp/qigsaw1.0.0/ && (cd `dirname .tmp/qigsaw1.0.0` && $(TAR) qigsaw1.0.0.tar qigsaw1.0.0 && $(COMPRESS) qigsaw1.0.0.tar) && $(MOVE) `dirname .tmp/qigsaw1.0.0`/qigsaw1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qigsaw1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_newdialog.cpp moc_jigsawaboutbox.cpp moc_mainwidget.cpp moc_previewframe.cpp moc_finaldialog.cpp moc_aqsound.cpp moc_qpreviewfiledialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_newdialog.cpp moc_jigsawaboutbox.cpp moc_mainwidget.cpp moc_previewframe.cpp moc_finaldialog.cpp moc_aqsound.cpp moc_qpreviewfiledialog.cpp
moc_mainwindow.cpp: mainwindow.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_newdialog.cpp: newdialog.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) newdialog.h -o moc_newdialog.cpp

moc_jigsawaboutbox.cpp: jigsawaboutbox.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) jigsawaboutbox.h -o moc_jigsawaboutbox.cpp

moc_mainwidget.cpp: mainwidget.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) mainwidget.h -o moc_mainwidget.cpp

moc_previewframe.cpp: previewframe.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) previewframe.h -o moc_previewframe.cpp

moc_finaldialog.cpp: finaldialog.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) finaldialog.h -o moc_finaldialog.cpp

moc_aqsound.cpp: aqsound.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) aqsound.h -o moc_aqsound.cpp

moc_qpreviewfiledialog.cpp: qpreviewfiledialog.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) qpreviewfiledialog.h -o moc_qpreviewfiledialog.cpp

compiler_rcc_make_all: qrc_qigsaw.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qigsaw.cpp
qrc_qigsaw.cpp: qigsaw.qrc \
		qigsaw_ru.qm \
		qigsaw_be.qm \
		txt/copying_ru \
		txt/copying_en \
		pics/info.png \
		pics/about.png \
		pics/transparent.png \
		pics/fit.png \
		pics/hint.png \
		pics/filesave.png \
		pics/fileopen.png \
		pics/viewpic.png \
		pics/sound.png \
		pics/preview.png \
		pics/cancel.png \
		pics/checked.png \
		pics/filenew.png \
		pics/help.png \
		audio/click.wav
	/usr/lib/qt4/bin/rcc -name qigsaw qigsaw.qrc -o qrc_qigsaw.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_NewDialog.h ui_jigsawaboutbox.h ui_mainwidget.h ui_previewframe.h ui_finaldialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_NewDialog.h ui_jigsawaboutbox.h ui_mainwidget.h ui_previewframe.h ui_finaldialog.h
ui_mainwindow.h: mainwindow.ui
	/usr/lib/qt4/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_NewDialog.h: NewDialog.ui
	/usr/lib/qt4/bin/uic NewDialog.ui -o ui_NewDialog.h

ui_jigsawaboutbox.h: jigsawaboutbox.ui
	/usr/lib/qt4/bin/uic jigsawaboutbox.ui -o ui_jigsawaboutbox.h

ui_mainwidget.h: mainwidget.ui
	/usr/lib/qt4/bin/uic mainwidget.ui -o ui_mainwidget.h

ui_previewframe.h: previewframe.ui
	/usr/lib/qt4/bin/uic previewframe.ui -o ui_previewframe.h

ui_finaldialog.h: finaldialog.ui
	/usr/lib/qt4/bin/uic finaldialog.ui -o ui_finaldialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		newdialog.h \
		ui_mainwindow.h \
		jigsawaboutbox.h \
		previewframe.h \
		preview.h \
		qpreviewfiledialog.h \
		mainwidget.h \
		JigsawCutter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

SquareCutter.o: SquareCutter.cpp SquareCutter.h \
		JigsawCutter.h \
		exceptions.h \
		Piece.h \
		TDArray.h \
		JigUtil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SquareCutter.o SquareCutter.cpp

RectCutter.o: RectCutter.cpp RectCutter.h \
		JigsawCutter.h \
		exceptions.h \
		JigUtil.h \
		Piece.h \
		TDArray.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RectCutter.o RectCutter.cpp

QuadCutter.o: QuadCutter.cpp QuadCutter.h \
		JigsawCutter.h \
		exceptions.h \
		JigUtil.h \
		Piece.h \
		TDArray.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QuadCutter.o QuadCutter.cpp

Piece.o: Piece.cpp Piece.h \
		MultiPiece.h \
		exceptions.h \
		JigUtil.h \
		IGap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Piece.o Piece.cpp

NoRotationsShuffler.o: NoRotationsShuffler.cpp NoRotationsShuffler.h \
		JigShuffler.h \
		Piece.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NoRotationsShuffler.o NoRotationsShuffler.cpp

MultiPiece.o: MultiPiece.cpp MultiPiece.h \
		Piece.h \
		exceptions.h \
		JigUtil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MultiPiece.o MultiPiece.cpp

Knob.o: Knob.cpp Knob.h \
		exceptions.h \
		JigUtil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Knob.o Knob.cpp

JigUtil.o: JigUtil.cpp JigUtil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o JigUtil.o JigUtil.cpp

JigShuffler.o: JigShuffler.cpp JigShuffler.h \
		Piece.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o JigShuffler.o JigShuffler.cpp

JigsawCutter.o: JigsawCutter.cpp JigsawCutter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o JigsawCutter.o JigsawCutter.cpp

IGap.o: IGap.cpp IGap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o IGap.o IGap.cpp

FreeShuffler.o: FreeShuffler.cpp FreeShuffler.h \
		JigShuffler.h \
		Piece.h \
		JigUtil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FreeShuffler.o FreeShuffler.cpp

FreeCenterShuffler.o: FreeCenterShuffler.cpp FreeCenterShuffler.h \
		JigShuffler.h \
		Piece.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FreeCenterShuffler.o FreeCenterShuffler.cpp

exceptions.o: exceptions.cpp exceptions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o exceptions.o exceptions.cpp

ClassicCutter.o: ClassicCutter.cpp ClassicCutter.h \
		JigsawCutter.h \
		exceptions.h \
		JigUtil.h \
		Piece.h \
		Knob.h \
		TDArray.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ClassicCutter.o ClassicCutter.cpp

Classic4Cutter.o: Classic4Cutter.cpp Classic4Cutter.h \
		JigsawCutter.h \
		exceptions.h \
		JigUtil.h \
		Piece.h \
		Knob.h \
		TDArray.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Classic4Cutter.o Classic4Cutter.cpp

ByColorShuffler.o: ByColorShuffler.cpp ByColorShuffler.h \
		JigShuffler.h \
		Piece.h \
		IGap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ByColorShuffler.o ByColorShuffler.cpp

newdialog.o: newdialog.cpp newdialog.h \
		ui_NewDialog.h \
		Classic4Cutter.h \
		JigsawCutter.h \
		ClassicCutter.h \
		SquareCutter.h \
		RectCutter.h \
		QuadCutter.h \
		preview.h \
		qpreviewfiledialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o newdialog.o newdialog.cpp

jigsawaboutbox.o: jigsawaboutbox.cpp jigsawaboutbox.h \
		ui_jigsawaboutbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jigsawaboutbox.o jigsawaboutbox.cpp

mainwidget.o: mainwidget.cpp mainwidget.h \
		ui_mainwidget.h \
		mainwindow.h \
		JigsawCutter.h \
		Piece.h \
		FreeShuffler.h \
		JigShuffler.h \
		FreeCenterShuffler.h \
		NoRotationsShuffler.h \
		JigUtil.h \
		ByColorShuffler.h \
		finaldialog.h \
		MultiPiece.h \
		aqsound.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwidget.o mainwidget.cpp

previewframe.o: previewframe.cpp previewframe.h \
		ui_previewframe.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o previewframe.o previewframe.cpp

finaldialog.o: finaldialog.cpp finaldialog.h \
		ui_finaldialog.h \
		mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o finaldialog.o finaldialog.cpp

preview.o: preview.cpp preview.h \
		qpreviewfiledialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o preview.o preview.cpp

aqsound.o: aqsound.cpp aqsound.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aqsound.o aqsound.cpp

qpreviewfiledialog.o: qpreviewfiledialog.cpp qpreviewfiledialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qpreviewfiledialog.o qpreviewfiledialog.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_newdialog.o: moc_newdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_newdialog.o moc_newdialog.cpp

moc_jigsawaboutbox.o: moc_jigsawaboutbox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_jigsawaboutbox.o moc_jigsawaboutbox.cpp

moc_mainwidget.o: moc_mainwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwidget.o moc_mainwidget.cpp

moc_previewframe.o: moc_previewframe.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_previewframe.o moc_previewframe.cpp

moc_finaldialog.o: moc_finaldialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_finaldialog.o moc_finaldialog.cpp

moc_aqsound.o: moc_aqsound.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aqsound.o moc_aqsound.cpp

moc_qpreviewfiledialog.o: moc_qpreviewfiledialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qpreviewfiledialog.o moc_qpreviewfiledialog.cpp

qrc_qigsaw.o: qrc_qigsaw.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qigsaw.o qrc_qigsaw.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

